export const APPEND_QUESTIONS = 'APPEND_QUESTIONS'
export const APPEND_USERS = 'APPEND_USERS'
export const APPEND_USER_QUESTIONS = 'APPEND_USER_QUESTIONS'
export const REFRESH_USER = 'REFRESH_USER'
export const REFRESH_USERS = 'REFRESH_USERS'
export const REFRESH_QUESTION = 'REFRESH_QUESTION'
export const REFRESH_QUESTIONS = 'REFRESH_QUESTIONS'
export const REFRESH_SCHOOL = 'REFRESH_SCHOOL'
export const REFRESH_USER_QUESTIONS = 'REFRESH_USER_QUESTIONS'
export const UPDATE_PAGE_HOT_LOADING = 'UPDATE_PAGE_HOT_LOADING'
export const UPDATE_PAGE_USERS = 'UPDATE_PAGE_USERS'
export const UPDATE_PAGE_USERS_LOADING = 'UPDATE_PAGE_USERS_LOADING'
export const UPDATE_PAGE_ME = 'UPDATE_PAGE_ME'
export const UPDATE_PAGE_ME_LOADING = 'UPDATE_PAGE_ME_LOADING'
export const TOGGLE_PAGE_LOADING = 'TOGGLE_PAGE_LOADING'

export const PAGES = {
  HOT: 'HOT',
  USERS: 'USERS',
  ME: 'ME'
}