export const APPEND_QUESTIONS = 'APPEND_QUESTIONS'
export const APPEND_USERS = 'APPEND_USERS'
export const REFRESH_USER = 'REFRESH_USER'
export const REFRESH_QUESTION = 'REFRESH_QUESTION'
export const REFRESH_PAGE_HOT_LIST = 'REFRESH_PAGE_HOT_LIST'
export const REFRESH_PAGE_USERS_LIST = 'REFRESH_PAGE_USERS_LIST'
export const UPDATE_PAGE_HOT = 'UPDATE_PAGE_HOT'
export const UPDATE_PAGE_USERS = 'UPDATE_PAGE_USERS'
export const UPDATE_PAGE_ME = 'UPDATE_PAGE_ME'
export const TOGGLE_PAGE_LOADING = 'TOGGLE_PAGE_LOADING'

export const PAGES = {
  HOT: 'HOT',
  USERS: 'USERS',
  ME: 'ME'
}